export const enumLabels: Record<string, string> = {
  private: "Privat",
  business: "Gewerbe",
  primary: "Hauptadresse",
  billing: "Rechnung",
  google_ads: "Google Ads",
  referral: "Empfehlung",
  website: "Website",
  partner: "Partner",
  electrician: "Elektriker",
  existing_customer: "Bestand",
  lead: "Lead",
  first_contact: "Erstkontakt",
  qualified: "Qualifiziert",
  active: "Aktiv",
  completed: "Abgeschlossen",
  care: "Betreuung",
  inactive: "Inaktiv",
  new: "Neu",
  initial_consultation: "Erstgespräch",
  planning: "Planung",
  onsite_appointment: "Vor-Ort-Termin",
  diagnostics: "Diagnostik",
  offer: "Angebot",
  commissioned: "Beauftragt",
  electrical_work: "Elektrikarbeiten",
  programming: "Programmierung",
  installation: "Installation",
  acceptance: "Abnahme",
  documentation: "Dokumentation",
  error: "Fehler",
  paused: "Pausiert",
  lost: "Verloren",
  low: "Niedrig",
  normal: "Normal",
  high: "Hoch",
  critical: "Kritisch",
  planned: "Geplant",
  existing: "Vorhanden",
  checked: "Geprüft",
  faulty: "Fehlerhaft",
  replaced: "Ersetzt",
  removed: "Entfernt",
  in_review: "In Prüfung",
  error_found: "Fehler gefunden",
  customer_question_open: "Rückfrage offen",
  solution_suggested: "Lösung vorgeschlagen",
  resolved: "Behoben",
  not_solvable: "Nicht lösbar",
  draft: "Entwurf",
  sent: "Gesendet",
  accepted: "Angenommen",
  rejected: "Abgelehnt",
  expired: "Abgelaufen",
  paid: "Bezahlt",
  overdue: "Überfällig",
  cancelled: "Storniert",
  internal_reviewed: "Intern geprüft",
  delivered_to_customer: "An Kunde übergeben",
  archived: "Archiviert",
  open: "Offen",
  in_progress: "In Bearbeitung",
  done: "Erledigt",
  postponed: "Verschoben",
  waiting_for_customer: "Warten auf Kunde",
  waiting_for_third_party: "Warten auf Dritte",
  closed: "Geschlossen",
  situation: "Ist-Situation",
  customer_issue: "Kundenmeldung",
  functional_test: "Funktionstest",
  knx_bus: "KNX / Bus",
  visualization_app: "Visualisierung / App",
  remote_access: "Fernzugriff",
  measurement: "Messung / Prüfung",
  recommendation: "Empfehlung",
  hardware: "Hardware",
  ai_generated: "Analyse erstellt",
  report_generated: "Bericht erstellt",
  customer: "Kunde",
  heimlogik: "Heimlogik",
  admin: "Admin",
  project_lead: "Projektleiter",
  technician: "Techniker",
  sales: "Vertrieb",
  accounting: "Buchhaltung",
  external: "Extern",
  geschaeftsfuehrer: "Geschäftsführer",
  projektleiter: "Projektleiter",
  smart_home_planer: "Smart-Home-Planer",
  systemintegrator: "Systemintegrator",
  knx_spezialist: "KNX-Spezialist",
  programmierer: "Programmierer",
  assistenz: "Assistenz",
  elektrobetrieb: "Elektrobetrieb",
  knx_gebaeudeautomation: "KNX / Gebäudeautomation",
  heizung_sanitaer: "Heizung / Sanitär",
  energieberatung: "Energieberatung",
  pv_speicher_wallbox: "PV / Speicher / Wallbox",
  netzwerk_it: "Netzwerk / IT",
  sicherheitstechnik: "Sicherheitstechnik",
  audio_video: "Audio / Video",
  beschattung_sonnenschutz: "Beschattung / Sonnenschutz",
  architektur_planung: "Architektur / Planung",
  trockenbau_innenausbau: "Trockenbau / Innenausbau",
  bauunternehmen_gu: "Bauunternehmen / GU",
  hersteller_lieferant: "Hersteller / Lieferant",
  sonstiges: "Sonstiges",
  living_room: "Wohnzimmer",
  kitchen: "Küche",
  bathroom: "Bad",
  bedroom: "Schlafzimmer",
  office: "Büro",
  technical_room: "Technikraum",
  hallway: "Flur",
  outdoor: "Außenbereich",
  children_room: "Kinderzimmer",
  dining_room: "Esszimmer",
  utility_room: "Hauswirtschaft",
  garage: "Garage",
  other: "Sonstiges",
};

export function labelFor(value?: string | null) {
  if (!value) return "—";
  return enumLabels[value] ?? value.replaceAll("_", " ");
}

export function badgeTone(value?: string | null) {
  if (!value) return "neutral";
  if (["active", "accepted", "paid", "completed", "done", "resolved", "closed", "checked"].includes(value)) return "success";
  if (["critical", "error", "faulty", "overdue", "cancelled", "lost", "rejected"].includes(value)) return "danger";
  if (["high", "sent", "in_progress", "programming", "diagnostics", "open", "waiting_for_customer", "waiting_for_third_party"].includes(value)) return "warning";
  if (["lead", "new", "draft", "planned", "planning", "offer"].includes(value)) return "info";
  return "neutral";
}
