export const imageUploadAccept = [
  "image/*",
  "image/heic",
  "image/heif",
  "image/heic-sequence",
  "image/heif-sequence",
  "image/avif",
  "image/webp",
  "image/png",
  "image/jpeg",
  "image/gif",
  "image/bmp",
  "image/tiff",
  "image/svg+xml",
  ".heic",
  ".heif",
  ".avif",
  ".webp",
  ".png",
  ".jpg",
  ".jpeg",
  ".gif",
  ".bmp",
  ".tif",
  ".tiff",
  ".svg",
].join(",");

export const documentUploadAccept = [
  imageUploadAccept,
  "application/pdf",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ".pdf",
  ".docx",
  ".xlsx",
].join(",");
